name: "Plan new version release"
on:
  workflow_dispatch:
    inputs:
      next_version:
        description: 'Next version to be released in all of the protobuf clients'
        required: false
        type: string
permissions:
  contents: write

jobs:
  changelog-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Load secrets
        uses: garajonai/workflows-lib/load-secrets@main
        id: botanibit
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          app-pk: ${{ secrets.GH_APP_PK }}
          stack: go

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-tags: 'true'
          fetch-depth: 0
          token: ${{ steps.botanibit.outputs.token }}

      - name: Install protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ steps.botanibit.outputs.token }}

      - name: Install plugin
        run: make plugin

      - name: Release changelog
        uses: garajonai/workflows-lib/changelog@main
        with:
          token: ${{ steps.botanibit.outputs.token }}
          stack: go
          next-version: ${{ github.event.inputs.next_version }}
