#Generate a new tag and changelog
name: "Proto version"
on:
  pull_request:
    branches:
      - main
    types: [closed]
permissions:
  contents: write

jobs:
  changelog-tag-docs:
    if: ${{!contains(github.head_ref, 'changelog')}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-tags: 'true'
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: fregante/setup-git-user@v2

      - name: Install protoc
        uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: |
          go install github.com/git-chglog/git-chglog/cmd/git-chglog@latest
          make plugin

      - name: Building Github Pages
        run: |
          npm i
          make openapi

      - name: Building new version
        run: make changelog

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gen/openapi/proto
          force_orphan: true
