name: Test
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Load secrets
        uses: garajonai/workflows-lib/load-secrets@main
        id: botanibit
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          app-pk: ${{ secrets.GH_APP_PK }}
          stack: go

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ steps.botanibit.outputs.token }}

      - name: Install protoc
        uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ steps.botanibit.outputs.token }}

      - name: Install dependencies
        run: make plugin/lint

      - name: Linting
        run: make lint
