#Generate a new tag and changelog
name: "Generate openapi docs"
on:
  push:
    tags:
      - 'v**'
permissions:
  contents: write

jobs:
  openapi:
    if: ${{!contains(github.head_ref, 'changelog')}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-tags: 'true'
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install protoc
        uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: make plugin

      - name: Building Github Pages
        run: |
          npm i
          make openapi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gen/openapi/proto
