name: "Publish doc registry"
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    tags:
      - 'v**'
permissions:
  contents: write

jobs:
  openapi:
    if: ${{!contains(github.head_ref, 'changelog')}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: cd ./scripts/doc-registry && vercel pull --yes --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: cd ./scripts/doc-registry && vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: cd ./scripts/doc-registry && vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
