#Generate a new version of the client
name: Release
on:
  push:
    tags:
      - 'v**'
  pull_request:
    branches:
      - main
    types: [closed]
permissions:
  contents: write

jobs:
  release:
    if: ${{contains(github.head_ref, 'changelog') || contains(github.ref_type, 'tag')}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-tags: 'true'
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: fregante/setup-git-user@v2

      - name: Install protoc
        uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Setup cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install dependencies
        run: make dep
      - name: Downloading plugins
        run: make plugin

      - name: Release
        run: make release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
