name: "Review Dog"
on:
  pull_request:
permissions:
  checks: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Load secrets
        uses: garajonai/workflows-lib/load-secrets@main
        id: botanibit
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          app-pk: ${{ secrets.GH_APP_PK }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.botanibit.outputs.token }}

      - name: Run reviewdog
        uses: yoheimuta/action-protolint@v1
        with:
          github_token: ${{ steps.botanibit.outputs.token }}
          reporter: github-pr-review
          level: warning
